#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["ApiGateways/Shopping.AggregatorApi/Shopping.AggregatorApi.csproj", "ApiGateways/Shopping.AggregatorApi/"]
RUN dotnet restore "ApiGateways/Shopping.AggregatorApi/Shopping.AggregatorApi.csproj"
COPY . .
WORKDIR "/src/ApiGateways/Shopping.AggregatorApi"
RUN dotnet build "Shopping.AggregatorApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Shopping.AggregatorApi.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Shopping.AggregatorApi.dll"]