FROM mcr.microsoft.com/dotnet/sdk:6.0
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 5000
ENV ASPNETCORE_URLS=http://+:5000

WORKDIR /src
COPY ["Services/Catalog/Catalog.Api/Catalog.Api.csproj", "Services/Catalog/Catalog.Api/"]
RUN dotnet restore "Services/Catalog/Catalog.Api/Catalog.Api.csproj"
COPY . .
WORKDIR "/src/Services/Catalog/Catalog.Api"
RUN dotnet build -c Debug /p:UseAppHost=false

ENTRYPOINT ["dotnet", "run", "-c", "Debug", "Basket.Api.dll"]