version: '3.4'

services:
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8888:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catalogdb_data:/data/db

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=mongodb://catalogdb:27017
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - basketdb_data:/usr/local/etc/redis

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__ConnectionString=basketdb:6379
      - DiscountServiceHost=http://discount.grpc
    depends_on:
      - basketdb
    ports:
      - "8001:80"

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123456
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - discountdb_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=sounj142@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin123456
    restart: always
    depends_on:
      - discountdb
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin123456;
    depends_on:
      - discountdb
    ports:
      - "8002:80"

  orderdb:
    container_name: orderdb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"
    volumes:
      - orderdb_data:/var/opt/mssql

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678;Trust Server Certificate=true;
      - EmailSettings__ApiKey=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
    depends_on:
      - orderdb
    ports:
      - "8004:80"
